TechJobsPersistent/Models/ErrorViewModel.cs
using System;

namespace TechJobsPersistent.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TechJobsPersistent/ViewModels/AddEmployerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace TechJobsPersistent.ViewModels
{
    public class AddEmployerViewModel
    {
        [Required(ErrorMessage ="Every Job must have a Name!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Every Job must have a Location!")]
        public string Location { get; set; }

    }
}

TechJobsPersistent/ViewModels/AddJobViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TechJobsPersistent.Models;

namespace TechJobsPersistent.ViewModels
{
    public class AddJobViewModel
    {
        [Required(ErrorMessage = "A Name is required")]
        public string Name { get; set; }

        public int EmployerId { get; set; }

        public List<SelectListItem> Employers { get; set; }

        public List<Skill> Skills { get; set; }

        public AddJobViewModel() { }

        public AddJobViewModel(List<Employer> employers, List<Skill> skills)
        {

            this.Skills = skills;

            this.Employers = new List<SelectListItem>();

            foreach (Employer employer in employers)
            {
                this.Employers.Add(
                    new SelectListItem
                    {
                        Value = employer.Id.ToString(),
                        Text = employer.Name
                    });
            }
        }

    }
}

TechJobsPersistent/Controllers/EmployerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TechJobsPersistent.Data;
using TechJobsPersistent.Models;
using TechJobsPersistent.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TechJobsPersistent.Controllers
{
    public class EmployerController : Controller
    {
        private JobDbContext _context;

        public EmployerController(JobDbContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Employer> employers = _context.Employers.ToList();
            
            return View(employers);
        }

        public IActionResult Add()
        {
            AddEmployerViewModel addEmployerViewModel = new AddEmployerViewModel();
            
            return View(addEmployerViewModel);
        }

        public IActionResult ProcessAddEmployerForm(AddEmployerViewModel addEmployerViewModel)
        {
            if(ModelState.IsValid)
            {
                Employer employer = new Employer
                {
                    Name = addEmployerViewModel.Name,
                    Location = addEmployerViewModel.Location
                };

                _context.Employers.Add(employer);
                _context.SaveChanges();

                return Redirect("/Employer");
            }
            
            return View("~/Views/Employer/Add.cshtml", addEmployerViewModel);
        }

        public IActionResult About(int id)
        {
            Employer employer = _context.Employers.Find(id);
            
            return View(employer);
        }
    }
}

TechJobsPersistent/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TechJobsPersistent.Models;
using TechJobsPersistent.ViewModels;
using TechJobsPersistent.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace TechJobsPersistent.Controllers
{
    public class HomeController : Controller
    {
        private JobDbContext _context;

        public HomeController(JobDbContext dbContext)
        {
            _context = dbContext;
        }

        public IActionResult Index()
        {
            List<Job> jobs = _context.Jobs.Include(j => j.Employer).ToList();

            return View(jobs);
        }

        [HttpGet("/Add")]
        public IActionResult AddJob()
        {
            List<Employer> employers = _context.Employers.ToList();
            List<Skill> skills = _context.Skills.ToList();

            AddJobViewModel addJobViewModel = new AddJobViewModel(employers, skills);

            return View(addJobViewModel);
        }

        public IActionResult ProcessAddJobForm(AddJobViewModel addJobViewModel, string[] selectedSkills)
        {
            Employer theEmployer = _context.Employers.Find(addJobViewModel.EmployerId);

            if (ModelState.IsValid)
            {
                Job newJob = new Job
                {
                    Name = addJobViewModel.Name,
                    EmployerId = addJobViewModel.EmployerId,
                    Employer = theEmployer
                };

                _context.Jobs.Add(newJob);
                _context.SaveChanges();

                foreach (string skill in selectedSkills)
                {
                    JobSkill newJobSkill = new JobSkill
                    {
                        Job = newJob,
                        JobId = newJob.Id,
                        SkillId = Int32.Parse(skill)
                    };

                    _context.JobSkills.Add(newJobSkill);
                }

                return Redirect("Index");
            }

            return View(addJobViewModel);
        }

        public IActionResult Detail(int id)
        {
            Job theJob = _context.Jobs
                .Include(j => j.Employer)
                .Single(j => j.Id == id);

            List<JobSkill> jobSkills = _context.JobSkills
                .Where(js => js.JobId == id)
                .Include(js => js.Skill)
                .ToList();

            JobDetailViewModel viewModel = new JobDetailViewModel(theJob, jobSkills);
            return View(viewModel);
        }
    }
}

TechJobsPersistent/Views/Employer/About.cshtml
@model TechJobsPersistent.Models.Employer

<h1>Employer: @Model.Name</h1>

<div>
    <p>Name: @Model.Name</p>
    <p>Location: @Model.Location</p>
</div>

TechJobsPersistent/Views/Employer/Add.cshtml
@model TechJobsPersistent.ViewModels.AddEmployerViewModel

<h1>Add New Employer</h1>

<form asp-controller="Employer" asp-action="ProcessAddEmployerForm" method="post">
    <div class="form-group">
        <label asp-for="Name">Employer Name</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Location">Employer Location</label>
        <input asp-for="Location" />
        <span asp-validation-for="Location"></span>
    </div>
    <input type="submit" value="Submit" />
</form>

TechJobsPersistent/Views/Home/AddJob.cshtml
@model TechJobsPersistent.ViewModels.AddJobViewModel

<h1>Add a Job</h1>

<form asp-controller="Home"
      asp-action="ProcessAddJobForm"
      method="post">
    <div class="form-group">

        <label asp-for="Name">Name</label>

        <input class="form-control" asp-for="Name" />

        <span asp-validation-for="Name"></span>

    </div>

    <div class="form-group">
        <label asp-for="EmployerId">Employer</label>

        <select asp-for="EmployerId" asp-items="Model.Employers">
        </select>
    </div>

    <div class="form-group">
        @foreach (Skill skill in Model.Skills)
        {
            <label for="@skill.Id">@skill.Name</label>
            <input type="checkbox"
                   name="selectedSkills"
                   value="@skill.Id" />
        }
    </div>

    <input type="submit" value="Add Job" />
</form>

<br />

<div>
    <a asp-controller="Employer" asp-action="Add">Create a New Employer</a>
</div>

<br />

<div>
    <a asp-controller="Skill" asp-action="Add">Create a New Skill</a>
</div>

TechJobsPersistent/Views/Home/Detail.cshtml
@model TechJobsPersistent.ViewModels.JobDetailViewModel

<h1>@Model.Name</h1>

<table class="table">
    <tr>
        <th>Employer</th>
        <td>@Model.EmployerName</td>
    </tr>
    <tr>
        <th>Skills</th>
        <td>@Model.SkillText</td>
    </tr>

</table>

<a asp-controller="Skill" asp-action="AddJob" asp-route-id="@Model.JobId">Add additional skills</a>

TechJobsPersistent/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<TechJobsPersistent.Models.Job>

<div class="text-center">
    <h1 class="display-4">Welcome to TechJobs!</h1>
    <p><a asp-controller="Home" asp-action="AddJob">Add Jobs</a></p>
    <p><a asp-controller="List" asp-action="Index">List Jobs</a></p>
    <p><a asp-controller="Search" asp-action="Index">Search Jobs</a></p>
</div>

@if (Model.Count == 0)
{
    <p>No jobs yet!</p>
}
else
{
    <table class="table">
        <tr>
            <th>Position Name</th>
            <th>Employer</th>
        </tr>
        @foreach (Job job in Model)
        {
            <tr>
                <td><a asp-controller="Home" asp-action="Detail" asp-route-id="@job.Id">@job.Name</a></td>
                <td>@job.Employer.Name</td>
            </tr>
        }
    </table>
}

TechJobsPersistent/Views/List/Index.cshtml
<div class="container body-content">
    <h1>@ViewBag.title</h1>
    <h2 class="centered">View Jobs By Category</h2>
</div>

<table class="centeredTable">
    <tr>
        @foreach (var column in ViewBag.columns)
        {
            @if (column.Key != "all")
            {
                <th>@column.Value</th>
            }
        }
    </tr>
    <tr>
        @foreach (var category in ViewBag.tableChoices)
        {
            <td>
                <ul>
                    @if (category == "employer")
                    {
                        @foreach (var item in ViewBag.employers)
                        {
                            <li>
                                <a asp-controller="List" asp-action="Jobs" asp-route-column="@category" asp-route-value="@item.Name">@item.Name</a>
                            </li>
                        }
                    }
                    else
                    {
                        @foreach (var item in ViewBag.skills)
                        {
                            <li>
                                <a asp-controller="List" asp-action="Jobs" asp-route-column="@category" asp-route-value="@item.Name">@item.Name</a>
                            </li>
                        }
                    }

                </ul>
            </td>
        }
    </tr>
</table>

TechJobsPersistent/Views/List/Jobs.cshtml
<div class="container body-content">

    <h1>@ViewBag.title</h1>

    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Employer</th>
            <th>Skills</th>
        </tr>
        @foreach (var job in ViewBag.jobs)
        {
            <tr>
                <td>@job.JobId</td>
                <td>@job.Name</td>
                <td>@job.EmployerName</td>
                <td>@job.SkillText</td>
            </tr>
        }
    </table>

</div>

TechJobsPersistent/Views/Search/Index.cshtml
<div class="container body-content">

    <h1>@ViewBag.title</h1>

    <form action="/search/results" method="post">
        <h2>Search by:</h2>

        <p>
            @foreach (var column in ViewBag.columns)
            {
                <span>
                    <input type="radio" name="searchType" id="@column.Key" value="@column.Key" checked="@column.Key == 'all'" />
                    <label for="@column.Key">@column.Value</label>
                </span>
            }

        </p>

        <p>
            <label for="searchTerm">Keyword:</label>
            <input type="text" name="searchTerm" id="searchTerm" />
        </p>

        <input type="submit" value="Search" />
    </form>

    <hr />

    @if (ViewBag.jobs != null)
    {
        <table>
            @foreach (var job in ViewBag.jobs)
            {
                <tr>
                    <td>
                        <p>ID: @job.JobId</p>
                        <p>Name: @job.Name</p>
                        <p>Employer: @job.EmployerName</p>
                        <p>Location: @job.SkillText</p>
                    </td>
                </tr>
            }
        </table>
    }


</div>

TechJobsPersistent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechJobsPersistent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TechJobsPersistent</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AddJob">Add Job</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TechJobsPersistent
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TechJobsPersistent/Views/Skill/About.cshtml
@model List<TechJobsPersistent.Models.JobSkill>

@if (Model.Count == 0)
{
    <h1>No jobs with the given skill!</h1>
}
else
{
    <h1>Jobs with the Skill: @Model[0].Skill.Name</h1>
    <p>Skill Description: @Model[0].Skill.Description</p>

    <ul>
        @foreach (var jobSkill in Model)
        {
            <li>@jobSkill.Job.Name</li>
        }
    </ul>

}

TechJobsPersistent/Views/Skill/Add.cshtml
@model TechJobsPersistent.Models.Skill

<h1>Add New Skill</h1>

<form asp-controller="Skill" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name">Skill Name</label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Skill Description</label>
        <input asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
    <input type="submit" value="Submit" />
</form>

TechJobsPersistent/Views/Skill/AddJob.cshtml
@model TechJobsPersistent.ViewModels.AddJobSkillViewModel

<h1>Add Tag to Event: @Model.Job.Name</h1>

<form asp-controller="Skill" asp-action="AddJob" method="post">
    <input type="hidden" value="@Model.Job.Id" name="JobId" />
    <div class="form-group">
        <label asp-for="SkillId">Skill</label>
        <select asp-for="SkillId" asp-items="Model.Skills"></select>
        <span asp-validation-for="SkillId"></span>
    </div>
    <input type="submit" value="Add Skill" />
</form>

TechJobsPersistent/Views/Skill/Index.cshtml
@model List<TechJobsPersistent.Models.Skill>

<h1>In-demand Skills</h1>

<p><a asp-controller="Skill" asp-action="Add">Add a Skill</a></p>

@if (Model.Count == 0)
{
    <p>No skills are currently listed!</p>
}
else
{
    <div>
        <ul>
            @foreach (Skill skill in Model)
            {
                <li>
                    <a asp-controller="Skill" asp-action="About" asp-route-id="@skill.Id">@skill.Name</a>
                </li>
            }
        </ul>
    </div>
}